[package]
name = "native"
version = "0.1.0"
edition = "2021"

[dependencies]
example = { path = "../../features/example" }
mikros = { path = "../../../mikros" }
simple_api = { path = "../../features/simple_api" }
