[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
mikros = { path = "../../../" }
prost = "0.13.3"
tokio = { version = "1.41.1", features = ["full"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
