[package]
name = "cronjob_service"
version = "0.1.0"
edition = "2021"

[dependencies]
example = { path = "../../features/example" }
mikros = { path = "../../../mikros" }
cronjob = { path = "../../services/cronjob" }
simple_api = { path = "../../features/simple_api" }
