[package]
name = "http_with_state"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
axum = "0.7.7"
mikros = { path = "../../../" }
tokio = { version = "1.41.1", features = ["full"] }
tonic = "0.12.3"
futures = "0.3.31"
